# Generated by Django 3.0.7 on 2023-09-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Disciplina',
        ),
        migrations.RenameField(
            model_name='disciplina',
            old_name='codigo_curso',
            new_name='codigo_disciplina',
        ),
    ]
