# Generated by Django 3.0.7 on 2023-09-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230917_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamento',
            name='nome_treinamento',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
