# Generated by Django 3.0.7 on 2023-09-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_treinamento_nome_treinamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
