# Generated by Django 3.0.7 on 2023-09-20 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230919_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaTreinamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Aluno')),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Treinamento')),
            ],
        ),
    ]
