# Generated by Django 3.0.7 on 2023-09-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_matriculatreinamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatriculaTreinamento',
            new_name='Matricula',
        ),
    ]
