# Generated by Django 3.0.7 on 2023-09-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230921_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='codigo_curso',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
